# fly.toml app configuration file generated for folder-zone on 2025-12-23T14:38:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'folder-zone'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.tls_options]
    versions = ['TLSv1.3']

[[vm]]
  cpus = 2
  memory_mb = 2048
